version: '3.1'

services:
  redis:
    image: redis

  postgresdb:
    hostname: postgresdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

  api:
    build:
      dockerfile: Dockerfile.api_server
      context: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_PASS=password
    depends_on:
      - postgresdb

  worker:
    build:
      dockerfile: Dockerfile.celery_worker
      context: ./server
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_PASS=password
    depends_on:
      - postgresdb
