apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      # instance: test
  template:
    metadata:
      labels:
        app: db
        # instance: test
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
          # Name of PersistentVolumeClaim
            claimName: pvc-db
      containers:
        - name: db
          image: asia-south1-docker.pkg.dev/lp-wifi-350713/lp-wifi-docker-repo/postgres:1.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "100m"
