apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      instance: test
  template:
    metadata:
      labels:
        app: db
        instance: test
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
          # Name of PersistentVolumeClaim
            claimName: pvc-db
      containers:
        - name: db
          image: build-docker-stage.artifactory.eng.vmware.com/data_ingestor_db:0.0.1
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "100m"
