FROM python:3

WORKDIR /app

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["celery", "-A", "worker.celery", "worker", "--loglevel", "info"]